# Generated by Django 2.2.10 on 2020-02-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='タイトル')),
                ('content', models.TextField(max_length=5000, verbose_name='内容')),
                ('created_date', models.DateField(default='timezone.now', verbose_name='作成日')),
                ('updated_date', models.DateField(blank=True, null=True, verbose_name='更新日')),
                ('status', models.CharField(choices=[('考え中', 'Thinking'), ('作業中', 'Working'), ('完了', 'Finished')], default='考え中', max_length=3, verbose_name='ステータス')),
            ],
            options={
                'db_table': 'todolist',
            },
        ),
    ]
